- name: This removes an httpd webserver
  hosts: nodes
  tasks:
  - name: ensure httpd is stopped
    service:
      name: httpd 
      state: stopped
  - name: close port 80 for http access
    firewalld:
      service: http
      permanent: true
      state: disabled
  - name: Restart the firewalld service to load in the firewall changes
    service: 
      name: firewalld 
      state: restarted
  - name: Remove apache package
    yum:
      name: httpd
      autoremove: yes
      state: absent
  - name: remove index file
    file:
      path: /var/www/html/index.html
      state: absent

