#- name: Playbook for VSFTPD installation & configuration
#  hosts: node1.example.com
#  vars:
#    anonymous_enable: yes
#    local_enable: yes
#    write_enable: yes
#    anon_upload_enable: yes
#    services:
#      - vsftpd
#      - firewalld
#    packages:
#      - vsftpd
#      - firewalld
#    fileperms:
#      - /var/ftp/pub
#      - /var/ftp/pub/upload
#    ftpports:
#      - 20
#      - 21

#  tasks:
- name: Install required packages
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"

- name: Copy FTP config using Jinja2 Template
  template:
    src: vsftpd.j2
    dest: /etc/vsftpd/vsftpd.conf
  notify:
    - restart vsftpd

- name: Create ftp pub folder and set permissions
  file:
    path: /var/ftp/pub
    state: directory
    mode: 0755

- name: Creafe ftp upload folder and set permissions
  file:
    path: /var/ftp/pub/upload
    state: directory
    mode: 0777

- name: Set SElinux boolean for Anonymous FTP upload
  seboolean:
    name: ftpd_anon_write
    state: true
    persistent: yes
  tags:
   - sebool


#- name: Set SElinux boolean ftpd_full_access to ON
#  seboolean:
#    name: ftpd_full_access
#    state: yes
#    persistent: yes
#  tags:
#   - sebool

- name: setsebool ftpd_full_access on
  command: setsebool ftpd_full_access on


- name: Set SElinux file context
  sefcontext:
    target: "{{ item }}"
    setype: public_content_rw_t
    state: present
  loop: "{{ fileperms }}" 
  notify:
    - run restorecon

- name: Open firewall ports for FTP
  firewalld:
    service: ftp
    permanent: yes
    state: enabled
    immediate: yes


- name: "Add firewall rule for ports 20 and 21"
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
    immediate: yes
  loop: "{{ ftpports}}"
#notify: "Restart firewalld"
#ignore_errors: True


- name: Make sure services are started and enabled
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop: "{{ services }}"

    
#  handlers:
#  - name: run restorecon
#    command: restorecon -v /var/ftp/pub
#  - name: restart vsftpd
#    service:
#      name: vsftpd
#      state: restarted
